name: Release
run-name: Create Github release from tagged commit

# -- Trigger Events --------------------------------------------------------------------------------
on:
  workflow_dispatch:
  push:
    tags:
      - v*

# -- Concurrency -----------------------------------------------------------------------------------
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# -- Jobs ------------------------------------------------------------------------------------------
jobs:
  # Create Github release with changelog
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Pixi
        id: setup-pixi
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          cache: true
          locked: true
      - name: Install dependencies
        id: install-deps
        run: pixi install -e docs
      - name: Create changelog
        id: create-changelog
        run: pixi run -e docs changelog --latest --strip all --output ${{ github.workspace }}/changelog.md
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/changelog.md
